// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7tN0ArHWVeiW6xK1gC805XPdOhglXy_0',
    appId: '1:325188598280:web:3f262a38c1fc654324afbd',
    messagingSenderId: '325188598280',
    projectId: 'sender-sms-cde6b',
    authDomain: 'sender-sms-cde6b.firebaseapp.com',
    storageBucket: 'sender-sms-cde6b.firebasestorage.app',
    measurementId: 'G-VMNXX8EDBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCneG9fgcpNA1y3NN_lKqzjt_hXIp1LiJA',
    appId: '1:325188598280:android:b54748e35159c6b224afbd',
    messagingSenderId: '325188598280',
    projectId: 'sender-sms-cde6b',
    storageBucket: 'sender-sms-cde6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA00ZM81TORcpi5G143PDk61SXHSA1FHI',
    appId: '1:325188598280:ios:3fc32b8d53c0e11a24afbd',
    messagingSenderId: '325188598280',
    projectId: 'sender-sms-cde6b',
    storageBucket: 'sender-sms-cde6b.firebasestorage.app',
    iosBundleId: 'com.example.senderSms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA00ZM81TORcpi5G143PDk61SXHSA1FHI',
    appId: '1:325188598280:ios:3fc32b8d53c0e11a24afbd',
    messagingSenderId: '325188598280',
    projectId: 'sender-sms-cde6b',
    storageBucket: 'sender-sms-cde6b.firebasestorage.app',
    iosBundleId: 'com.example.senderSms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7tN0ArHWVeiW6xK1gC805XPdOhglXy_0',
    appId: '1:325188598280:web:2698ec43675a9c5424afbd',
    messagingSenderId: '325188598280',
    projectId: 'sender-sms-cde6b',
    authDomain: 'sender-sms-cde6b.firebaseapp.com',
    storageBucket: 'sender-sms-cde6b.firebasestorage.app',
    measurementId: 'G-DH6Z2LRD0Z',
  );
}
